"""NotebookGuide — an auto-generated overview of a project's sources.

One guide per project (summary + suggested questions), regenerated on demand once
sources are indexed. Mirrors NotebookLM's "Notebook guide". Generated by wrapping
Open Notebook's ask/search surface (see engines/open_notebook.py).
"""

from __future__ import annotations

import enum
import uuid
from typing import Any

from sqlalchemy import Enum, ForeignKey, JSON, String, Text, UniqueConstraint, Uuid
from sqlalchemy.orm import Mapped, mapped_column

from .base import Base, TimestampMixin, UpdatedAtMixin, UuidPkMixin


class GuideStatus(str, enum.Enum):
    pending = "pending"
    ready = "ready"
    failed = "failed"


class NotebookGuide(UuidPkMixin, TimestampMixin, UpdatedAtMixin, Base):
    __tablename__ = "notebook_guide"
    __table_args__ = (
        # Exactly one guide per project within a tenant.
        UniqueConstraint("tenant_id", "project_id", name="uq_guide_tenant_project"),
    )

    tenant_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True), ForeignKey("tenant.id"), nullable=False, index=True
    )
    project_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True), ForeignKey("project.id"), nullable=False, index=True
    )
    summary: Mapped[str | None] = mapped_column(Text, nullable=True)
    suggested_questions: Mapped[list[Any]] = mapped_column(JSON, default=list, nullable=False)
    status: Mapped[GuideStatus] = mapped_column(
        Enum(GuideStatus, name="guide_status"),
        default=GuideStatus.pending,
        nullable=False,
    )
    error: Mapped[str | None] = mapped_column(String(2000), nullable=True)

    def __repr__(self) -> str:  # pragma: no cover
        return f"<NotebookGuide project={self.project_id} status={self.status.value}>"
