"""Outline builders — produce a validated outline, governed or freeform.

`build_outline`: structure is derived from the profile's `section_structure` (fixed
order); the LLM only fills talking points. Deterministic structure across runs while
wording may vary. Retrieval context comes from Open Notebook. Result is validated
(and repaired onto the required structure if needed).

`build_freeform_outline` (DG-1): no profile, no fixed structure -- the LLM proposes
both in one call, from already-resolved content (see `content/resolver.py`). A draft
that fails validation is regenerated by the caller, not repaired, since there is no
fixed shape to repair onto.
"""

from __future__ import annotations

import re
import uuid
from collections.abc import Collection
from dataclasses import dataclass
from typing import Any, Protocol

from ..core.errors import ValidationError
from ..core.logging import get_logger
from ..models import StakeholderProfile
from .schema import (
    OUTLINE_SCHEMA_VERSION,
    DataBinding,
    OutlineContent,
    OutlineSection,
    TalkingPoint,
)
from .validator import repair_outline, validate_outline

logger = get_logger("orchestrator.outline")


@dataclass
class LlmResult:
    points_by_section: dict[str, list[str]]
    tokens_in: int
    tokens_out: int


@dataclass
class OutlineUsage:
    tokens_in: int
    tokens_out: int


@dataclass
class FreeformOutlineLlmResult:
    """Raw sections proposed by the model: [{"title": str, "bullets": [str, ...]}]."""

    sections: list[dict[str, Any]]
    tokens_in: int
    tokens_out: int


class FreeformOutlineLlm(Protocol):
    async def draft_outline(
        self,
        *,
        content: str,
        tone: str,
        density: str,
        n_slides_hint: int | None,
        language: str,
        provider_config: dict[str, Any],
    ) -> FreeformOutlineLlmResult: ...


class Llm(Protocol):
    async def talking_points(
        self,
        *,
        section_ids: list[str],
        context: list[dict[str, Any]],
        profile: dict[str, Any],
        provider_config: dict[str, Any],
    ) -> LlmResult: ...


def slugify(title: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-")
    return slug or "section"


def sections_from_profile(profile: StakeholderProfile) -> list[OutlineSection]:
    """Deterministic sections from the profile's pinned section_structure."""
    sections: list[OutlineSection] = []
    seen: dict[str, int] = {}
    for index, entry in enumerate(profile.section_structure or []):
        title = entry["title"] if isinstance(entry, dict) else str(entry)
        base = slugify(title)
        # Disambiguate duplicate titles deterministically.
        seen[base] = seen.get(base, 0) + 1
        sid = base if seen[base] == 1 else f"{base}-{seen[base]}"
        sections.append(OutlineSection(id=sid, title=title, order=index))
    return sections


def _retrieval_query(profile: StakeholderProfile) -> str:
    titles = ", ".join(
        (e["title"] if isinstance(e, dict) else str(e)) for e in profile.section_structure or []
    )
    return f"Key facts for an {profile.audience} presentation covering: {titles}"


def _profile_brief(profile: StakeholderProfile) -> dict[str, Any]:
    return {
        "audience": profile.audience,
        "tone": profile.tone.value,
        "verbosity": profile.verbosity.value,
        "language": profile.language,
        "prompt_config": profile.prompt_config,
    }


async def build_outline(
    *,
    project,
    profile: StakeholderProfile,
    on_client,
    llm: Llm,
    provider_config: dict[str, Any],
    allowed_source_refs: Collection[str],
) -> tuple[OutlineContent, OutlineUsage]:
    """Build a governed outline.

    `allowed_source_refs` scopes retrieval to the project's own sources; the engine's
    search index is shared across every project and tenant. Passed in rather than
    looked up here so the builder stays free of repository dependencies.
    """
    sections = sections_from_profile(profile)
    if not sections:
        raise ValidationError("Profile has no section_structure to build an outline from.")

    context: list[dict[str, Any]] = []
    if project.on_notebook_id:
        context = await on_client.search(
            allowed_source_refs=allowed_source_refs, query=_retrieval_query(profile)
        )

    result = await llm.talking_points(
        section_ids=[s.id for s in sections],
        context=context,
        profile=_profile_brief(profile),
        provider_config=provider_config,
    )

    valid_ids = {s.id for s in sections}
    talking_points = [
        TalkingPoint(section_id=sid, text=text)
        for sid, texts in result.points_by_section.items()
        if sid in valid_ids
        for text in texts
        if text
    ]
    data_bindings = _bindings_from_context(sections, context)

    content = OutlineContent(
        schema_version=OUTLINE_SCHEMA_VERSION,
        sections=sections,
        talking_points=talking_points,
        data_bindings=data_bindings,
    )

    model, errors = validate_outline(content.model_dump())
    if model is None:
        repaired = repair_outline(content.model_dump(), [s.title for s in sections])
        model, errors = validate_outline(repaired)
        if model is None:
            raise ValidationError(f"Could not build a valid outline: {errors}")

    return model, OutlineUsage(tokens_in=result.tokens_in, tokens_out=result.tokens_out)


def _bindings_from_context(
    sections: list[OutlineSection], context: list[dict[str, Any]]
) -> list[DataBinding]:
    """Bind the first section to available analysis refs as grounding provenance."""
    bindings: list[DataBinding] = []
    if not sections:
        return bindings
    for item in context:
        ref = item.get("source_ref")
        if ref:
            bindings.append(
                DataBinding(section_id=sections[0].id, key=f"fact-{uuid.uuid4().hex[:8]}", source_ref=ref)
            )
    return bindings


async def build_freeform_outline(
    *,
    content: str,
    tone: str,
    density: str,
    n_slides_hint: int | None,
    language: str,
    llm: FreeformOutlineLlm,
    provider_config: dict[str, Any],
) -> tuple[OutlineContent, OutlineUsage]:
    """Ungoverned outline (DG-1): one LLM call proposes structure AND wording.

    Unlike `build_outline`, there is no profile `section_structure` to fill in --
    structure has to come from the model itself. One call rather than the governed
    path's structure-then-wording split, both for token efficiency and because there
    is no fixed shape to hand the model up front. A draft the model can't turn into a
    valid outline is surfaced as a `ValidationError`, not repaired: `repair_outline`
    repairs onto a *fixed* title list, and there isn't one here -- the caller
    regenerates instead.
    """
    if not content.strip():
        raise ValidationError("No content to build an outline from.")

    result = await llm.draft_outline(
        content=content,
        tone=tone,
        density=density,
        n_slides_hint=n_slides_hint,
        language=language,
        provider_config=provider_config,
    )

    sections: list[OutlineSection] = []
    talking_points: list[TalkingPoint] = []
    seen: dict[str, int] = {}
    for raw in result.sections:
        if not isinstance(raw, dict):
            continue
        title = str(raw.get("title") or "").strip()
        if not title:
            continue
        base = slugify(title)
        seen[base] = seen.get(base, 0) + 1
        sid = base if seen[base] == 1 else f"{base}-{seen[base]}"
        sections.append(OutlineSection(id=sid, title=title, order=len(sections)))
        for bullet in raw.get("bullets") or []:
            # `None` stringifies to the literal text "None" -- skip it explicitly
            # rather than let str() turn a missing value into a fabricated bullet.
            if bullet is None:
                continue
            text = str(bullet).strip()
            if text:
                talking_points.append(TalkingPoint(section_id=sid, text=text))

    draft = OutlineContent(
        schema_version=OUTLINE_SCHEMA_VERSION,
        sections=sections,
        talking_points=talking_points,
        data_bindings=[],
    )

    model, errors = validate_outline(draft.model_dump())
    if model is None:
        raise ValidationError(f"Could not build a valid outline: {errors}")

    return model, OutlineUsage(tokens_in=result.tokens_in, tokens_out=result.tokens_out)
